!startuml er-example
!define uml https://raw.githubusercontent.com/flatring/plantuml-stencils/main
!include uml/colorset/ocean-blue.iuml
!include uml/colorset/_skinparams.iuml

actor Bob
participant Alice
participant WhiteRabbit
Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
Bob->WhiteRabbit: Log transaction
@enduml
